### ISSUE TITLE
Inconsistent with the results of Hung et al. paper

### ISSUE THREAD

**Issue by zhangbin0917** [sud0301/semisup-semseg#1]
I have noticed that the there are inconsistent with the results of Hung et al. [15] paper. Did you re-implement their code?

**Comment by sud0301** [comment]
Hi, All the results are consistent with the results of Hung et al. [15] paper. There is a difference in results for Cityscapes dataset since Hung et al. uses COCO pre-training and our results are produced without using COCO pre-training. For PASCAL-VOC dataset, we show both results with and without COCO pre-training. All the numbers for Hung et al. [15] are produced using their official repository.

**Comment by zhangbin0917** [comment]
Thank you for your reply.
I have another question. Have you run only one experiment for each number in the table? If it is yes, the result is very uncertain and not convincing. Should you set different seeds in different labeled data and unlabeled data to perform multiple experiments to calculate the mean and standard deviation?

**Comment by sud0301** [comment]
Each number is evaluated using three different splits and the mean value is reported.

**Comment by voldemortX** [comment]
For the PASCAL-VOC dataset, I wonder if your results of "without COCO pre-training" is even without ImageNet pre-training or the encoder part the network is still initialized with ImageNet pre-trained weights? Because the baseline 70.7% seems rather low.
